/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkforceRouteImport } from './routes/app.workforce'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppBroadcastsRouteImport } from './routes/app.broadcasts'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppActivitiesRouteImport } from './routes/app.activities'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkforceRoute = AppWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsRoute = AppBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/broadcasts': typeof AppBroadcastsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/broadcasts': typeof AppBroadcastsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/broadcasts': typeof AppBroadcastsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/activities'
    | '/app/analytics'
    | '/app/broadcasts'
    | '/app/compliance'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/settings'
    | '/app/tasks'
    | '/app/workforce'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/activities'
    | '/app/analytics'
    | '/app/broadcasts'
    | '/app/compliance'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/settings'
    | '/app/tasks'
    | '/app/workforce'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/activities'
    | '/app/analytics'
    | '/app/broadcasts'
    | '/app/compliance'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/settings'
    | '/app/tasks'
    | '/app/workforce'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workforce': {
      id: '/app/workforce'
      path: '/workforce'
      fullPath: '/app/workforce'
      preLoaderRoute: typeof AppWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/broadcasts': {
      id: '/app/broadcasts'
      path: '/broadcasts'
      fullPath: '/app/broadcasts'
      preLoaderRoute: typeof AppBroadcastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activities': {
      id: '/app/activities'
      path: '/activities'
      fullPath: '/app/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBroadcastsRoute: typeof AppBroadcastsRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorkforceRoute: typeof AppWorkforceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBroadcastsRoute: AppBroadcastsRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorkforceRoute: AppWorkforceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
